### ISSUE TITLE
Improve error messaging to provide guidance on `setup` or `start` failures

### ISSUE THREAD

**Issue by austinkelleher** [JupiterOne/starbase#15]
```
> yarn starbase run 
yarn run v1.22.4
$ ts-node ./src/index.ts run
Error: Starbase config file not found (filePath=config.yaml)
```

We should improve this message to explain the need for a `config.yaml` at the root of the Starbase project.

**Comment by adam-in-ict** [comment]
This was updated as part of https://github.com/JupiterOne/starbase/pull/47.  Closing until we identify additional updates/improvements we'd like for this.  Thanks!
