### ISSUE TITLE
Support `starbase wipe` command

### ISSUE THREAD

**Issue by austinkelleher** [JupiterOne/starbase#18]
We should support a `starbase wipe` command that allows wiping all Neo4j data or a subset of Neo4j data based on integration instance ID.

See: https://github.com/JupiterOne/sdk/blob/main/packages/integration-sdk-cli/src/commands/neo4j.ts#L44

**Comment by adam-in-ict** [comment]
Added as part of https://github.com/JupiterOne/starbase/pull/44
