### ISSUE TITLE
Support a Dockerized version of Starbase

### ISSUE THREAD

**Issue by austinkelleher** [JupiterOne/starbase#46]
Starbase requires multiple different dependencies (e.g. Node.js, yarn, etc.). Having a single Docker container that would allow execution of the Starbase CLI would be very helpful.

Example:

```sh
docker run --network="host" starbase:latest run
```

**Comment by adam-in-ict** [comment]
What do you think about something like the following command?  I could see it being nice to still have the .integrations folder as the working area, even when running via Docker.

`docker run --mount type=bind,source=$PWD/.integrations/,target=/opt/jupiterone/starbase/.integrations --network="host" starbase:latest run`

**Comment by adam-in-ict** [comment]
Made some updates in our docker working branch to support the command

`docker-compose run starbase run`

This leverages the default composer path of `docker-compose.yml`.  This additional file contains the volume mount, image name, and network mode settings to simplify the command line command.
