### ISSUE TITLE
Pipe the output of `exec()` commands to the terminal

### ISSUE THREAD

**Issue by ndowmon** [JupiterOne/starbase#5]
Is it possible to pipe the output of the `exec()` commands from `yarn starbase setup` and `yarn starbase update-integrations` to the terminal that’s running these commands?

```
➜  starbase git:(main) yarn starbase setup
yarn run v1.22.15
$ ts-node ./src/index.ts setup
✨  Done in 3.76s.
➜  starbase git:(main) yarn starbase update-integrations
yarn run v1.22.15
$ ts-node ./src/index.ts update-integrations
✨  Done in 18.40s.
```

For example, it’d be great to see the output of `yarn install` from each of the projects.

**Comment by adam-in-ict** [comment]
With the latest update, we're now pushing output to stdout.  It's currently not piped and won't show up until the command completes, so not truly being piped, but it does effectively add the same functionality.
