### ISSUE TITLE
Unable to setup config in 0.2.x

### ISSUE THREAD

**Issue by Nick-NCSU** [JupiterOne/starbase#67]
## **Description**
I am attempting to run a configuration containing one [qualys integration](https://github.com/JupiterOne/graph-qualys). On Starbase 0.1.0 (specifically starbase @ 0ae73bc but any 0.1 release should work) I am able to correctly setup Starbase.
![image](https://user-images.githubusercontent.com/65097490/166166084-7ec0f187-5856-47a1-b162-1c088f3cdc07.png)

However, on Starbase 0.2.x attempting to setup the same configuration file results in an error. (Screenshot from fresh install of 0.2.2 latest).
![image](https://user-images.githubusercontent.com/65097490/166166676-f8e82582-e7cd-489c-a7ca-68c4c13772c4.png)

The configuration file remained the same and the only difference is the version.

**Comment by adam-in-ict** [comment]
Hey Nick.  Thanks for the issue!

I did a bit of research into this and it appears to be Qualys specific.

Starting with version 0.2.0, we added in a step to dynamically import each project and if we could extract the `instanceConfigFields` we would use it to verify that the Starbase configuration for that specific project had the correct configuration values to be able to successfully run.

Unfortunately, this is triggering an error in the Qualys project on a deprecated RegExp .compile() call.  I'll get with our resident Qualys expert and determine if this is something we can tweak in Qualys or if it's an issue with how Starbase is importing/using it.

Thanks again for finding and documenting this!

**Comment by adam-in-ict** [comment]
Sorry for the delay getting an update, but as of this morning, I believe this particular issue should be fixed.  Using the latest version of graph-qualys, you should no longer be seeing an issue running `yarn starbase setup`.  I ran a quick test and was able to pull data.

**Comment by Nick-NCSU** [comment]
Thank you for the update, the issue seems to have been fixed!

**Comment by adam-in-ict** [comment]
Great!  Thanks for the confirmation!  Let us know if you run into any more issues
